### ISSUE TITLE
Error en la ejecución de Funciones

### ISSUE THREAD

**Issue by HectorMariano** [SlowAsteroid4/Calculadora#3]
El programa no es capaz de ejecutar las funciones implementadas. Anexo una captura del error encontrado

![unknown](https://user-images.githubusercontent.com/94412223/141875928-68cf0376-7431-4cd6-bef4-eee310397aac.png)

**Comment by DiegoFullen** [comment]
Se esta trabajando es solucionar el error
Gracias por su paciencia
